version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    # Другие настройки фронтэнда

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    # Другие настройки бэкэнда
