name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and publish Frontend
      working-directory: client
      run: |
        docker build -t frontend .
        docker run -d -p 3000:3000 frontend

    - name: Build and publish Backend
      working-directory: server
      run: |
        docker build -t backend .
        docker run -d -p 8080:8080 backend
